### PR TITLE
Add Events tab into UI

### PR DESCRIPTION
**Pull request by lucasponce**
Ok, a first Events tab to complete the details of what we show.
Mostly reused the Alerts tab and linked from Dashboard.
Ah, also put in order Dashboard, Alerts, Events as it is close and leave to the end the definitions/actions.

I'm going to optimize some missing formats on Events but in a following PR.

image

### CODE REVIEW

**Comment by lucasponce** [comment]
@jshaughn or @jmazzitelli please take a look. Thx.

**Comment by jshaughn** [comment]
LGTM for initial event support.

**Comment by jmazzitelli** [comment]
looks good. FYI: Jay has new date-time picker - he should add it to this new events page to replace the date picker here.

**Comment by lucasponce** [comment]
Yeah, I release the PR with minimal changes as I was aware Jay could be working on similar area.
So, to minimize conflicts you can rebase on this and add changes you need.

**Comment by jshaughn** [comment]
Yes, my goal is to have a global datetime range applied to the relevant pages by the end of today.

**Pull request merged**
