### PR TITLE
move to the new bus API v0.7.0

### PR DESCRIPTION
**Pull request by jmazzitelli**
This refactors the messages to use the new AbstractMessage (BasicMessage has been changed to be an interface)

### CODE REVIEW

**Comment by lucasponce** [comment]
Thx for the PR @jmazzitelli . I'm going to merge it after I finish a ActionHistory branch.
Main reason to wait is to not loose the -Prest profile we have there, as it has some integration tests needed for that branch, with this PR then I would need to re-arrange the profile to update manually the bus 0.7.0.
I will do it in one/two days.

**Comment by jshaughn** [comment]
Lucas, I merged your ActionHistory PR so you should be free to work on getting in this bus stuff.  Thanks, jay

**Comment by lucasponce** [comment]
I've resolved the conflicts manually and pushed on master.
Now alerts is synced with bus v0.7.0 API.

**Comment by pilhuhn** [comment]
I think that still needs a followup in hawkular/master ?

**Comment by lucasponce** [comment]
There is a PR un hawkular/master for it

**Pull request closed without merging**
