### PR TITLE
Spring cleaning

### PR DESCRIPTION
**Pull request by tsegismont**
Sorry for the PR name, I found it funny for some module changes at this time of year :wink: 

The PR has a few commits:
* Remove redundant groupId declaration in POMs
* Move action plugins into a sub-module and declare common dependencies
* Replace deprecated ANT "tasks" element with "target" element
* REST integration tests changes:
  * use ITest suffix, skip *ITest at test phase, then run *ITest with failsafe plugin
  * always compile groovy tests to avoid build warnings

### CODE REVIEW

**Comment by tsegismont** [comment]
I'm working on a last commit so that REST tests get executed on Travis (with the "rest" profile)

**Comment by jshaughn** [comment]
:Looks good to me so far, waiting to merge given that there is a pending commit.

**Comment by tsegismont** [comment]
Thanks for reviewing. The last commits should be pushed tomorrow. Have a nice weekend!


-----Original Message-----

**Comment by tsegismont** [comment]
So now the integration tests are in a new project, built at the end. This allows to use the Widlfly Maven plugin to start a nest, and deploy the alerts EAR, before executing the Groovy itests.

Note that Travis will fail, but this is "expected". There are two broken itests. I'll try to figure out what's wrong in the afternoon.

**Comment by tsegismont** [comment]
I was wrong in my previous comment, only now Travis should fail, because I've added the "rest" profile arguement in Travis YAML.

**Comment by tsegismont** [comment]
Turns out that the itests assume the presence of the sample data files. So now the Wildfly Maven plugin starts the nest with a custom data dir, where the sample data is deployed.

The PR is ready for final review/merging.

**Comment by lucasponce** [comment]
Hello Thomas,
I've reviewed the PR and I see some errors in the wildfly tests:
https://gist.github.com/lucasponce/8f8000361f74b5870b08

The tests executed but I wonder if you can take a look into these errors in the log.

**Comment by lucasponce** [comment]
thx @tsegismont for your commits !

**Pull request merged**
