### PR TITLE
Import WildFly BoM

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jshaughn could you please review and eventually merge?

**Comment by ppalaga** [comment]
@jshaughn is there anything blocking this PR? Not merging makes it hard for me to test subsequent changes in HK Parent.

**Comment by lucasponce** [comment]
Jay is on PTO until thursday and I will be back on monday. Can this PR
waits some days or it is urgent ?

**Comment by ppalaga** [comment]
Ah, OK, I will try find somebody else to review and merge, if you are both away. I supposed you have conflicting work in other branches that needs to go first. But if that is not the case, this one can go in. There should be nothing harmful inside.

**Comment by lucasponce** [comment]
I have to review an important PR on monday before this parent upgrade.
Again, how urgent is this one to change that order ?

**Comment by ppalaga** [comment]
No, it is not urgent. I can work it around till Monday. Enjoy your holiday!

**Comment by lucasponce** [comment]
Ok. Thanks, we will review it on monday morning.

**Pull request merged**
