### PR TITLE
HWKALERTS-33 Create an Aerogear sender plugin

### PR DESCRIPTION
**Pull request by tsegismont**
Create an Aerogear sender plugin

### CODE REVIEW

**Comment by tsegismont** [comment]
Just an initial commit with the project skeleton. Don't me misguided by the number of commits the GH GUI shows, I've checked out the new branch from the #35 Spring cleaning pull request. (Otherwise it will be hard to rebase). Once #35 is merged into the wintermute branch, I'll rebase this PR on wintermute.

**Comment by lucasponce** [comment]
I've merge the previous PR and fix a small thing in other file that shouldn't affect to the rebase of this one.
I can review it as soon you rebase it with wintermute branch.
Thx

**Comment by tsegismont** [comment]
The implementation is ready so the review can start. But please do not merge yet because I'm currently writing a unit test.

I've tested the implementation with Aerogear UPS 1.1.0-Alpha and a simple Android application.

**Comment by lucasponce** [comment]
thx !

**Pull request merged**
