### PR TITLE
Hwkalerts 54

### PR DESCRIPTION
**Pull request by jshaughn**
Refactor such that AlertsService and Impl does not handle both client requests and engine running concerns.  Allow client requests (like getAlerts) to be serviced by a pool of beans, while maintaining the singleton for the engine.

### CODE REVIEW

**Comment by lucasponce** [comment]
Hi Jay,
I'm reviewing this PR and I've seen a couple of things with the session that need to be fixed.
I've checkout your branch and I'm preparing a couple of commits to pile on that.

**Comment by lucasponce** [comment]
In particular I'm working in these commits:
- Makes a share session for keyspace, instead to have two as we have.
- The current PR needs to change that, if not a multiple session creation can lead into performance issues.
- If we separate all statements into CassStatement, I think we should refactor definitions as well, I think it's confusing to have splitted this.

I hope to have ready this fixes during the day.

**Comment by jshaughn** [comment]
OK, I was admittedly unsure about the Cassandra session handling and keyspace, so I'm glad you picked up on that.  I put a TODO in the code mentioning that we should probably consolidate all PreparedStatements into CassStatement.

**Comment by lucasponce** [comment]
+1
Thx for the changes !

**Pull request merged**
