### PR TITLE
Initial list of action history for selected timeline items.

### PR DESCRIPTION
**Pull request by jshaughn**

### CODE REVIEW

**Comment by jshaughn** [comment]
screen

**Comment by lucasponce** [comment]
If you use the example/autoresolve-process you can test it with a resolved alert.
Resolved Alert brings a new column on the Dashboard details and perhaps you can tweak in the actions are looking as you expect.
A minor one, in the Triggers/Actions I also used icons to represent the action plugin, visually is also interesting.
Perhaps we can bring the same icon of those pages here, too.
(I have also used icons for email and webhooks plugins).

**Comment by jshaughn** [comment]
With latest updates:

screen

**Comment by lucasponce** [comment]
LGTM
Perhaps the icon can be aligned on the actionId (like the user icon with the name).

**Comment by jshaughn** [comment]
> Perhaps the icon can be aligned on the actionId (like the user icon with the name).

I spent about an hour trying to get that to work nicely but failed.

**Pull request merged**
