### PR TITLE
Tutorial lesson 07 - Alerters

### PR DESCRIPTION
**Pull request by jshaughn**

### CODE REVIEW

**Comment by jshaughn** [comment]
@gbaufake , @lucasponce another tutorial lesson, this one is for external alerter.  Feel free to read through and comment on content, but don't yet try to run the example.   While developing the example I discovered a few issues in the hMetrics alerter.  The fixes for those will need to merged into metrics and I'll need a new docker container pushed to docker hub.  If you prefer to wait until it's all in place, that's fine, this is just letting you know about the new lesson.

**Comment by gbaufake** [comment]
@jshaughn 

I am running this tutorial on 
`{
  "distributed": "false",
  "Implementation-Version": "1.7.0.Final",
  "Built-From-Git-SHA1": "9a83f9f83b9b9d960916fec18c3d4084d03ac1d8",
  "status": "STARTED"
}`

with HTTP-Method: `http://localhost:8080/hawkular/alerts?tagQuery=lesson=7`
with `Hawkular-tenant: tutorial`

after a POST `http://localhost:8080/hawkular/alerts/triggers/trigger`
`{
"trigger": {
  "tenantId": "tutorial",
  "id": "lesson-07-trigger",
  "name": "Lesson 07 Trigger",
  "description": "Generates an alert on low median and high data point",
  "autoDisable": true,
  "enabled": false,
  "firingMatch": "ALL",
  "tags": {
    "HawkularMetrics": "MetricsCondition",
    "lesson": "7"
  }
},
"conditions": [
  {
    "triggerMode": "FIRING",
    "type": "EXTERNAL",
    "alerterId": "HawkularMetrics",
    "dataId": "alerterExpression01",
    "expression": "{\"queries\": [{\"name\":\"qNow\", \"type\":\"gauge\", \"metrics\":[\"gauge-1\"], \"percentiles\":[\"60\"], \"duration\":\"45s\"}], \"frequency\":\"15s\", \"eval\":\"(q(qNow,%60) < 40)\"}"
  },
  {
    "triggerMode": "FIRING",
    "type": "THRESHOLD",
    "dataId": "hm_g_gauge-2",
    "operator": "GTE",
    "threshold": 70
  }
]
}`

**Comment by jshaughn** [comment]
@gbaufake There was a silly mistake in the trigger definition. It is fixed and updated in the PR.  It is working for me. Give it another try and let me know, I think it will be fine and we can merge this lesson.

**Comment by gbaufake** [comment]
@jshaughn I got this a response

`[
    {
        "eventType": "ALERT",
        "tenantId": "tutorial",
        "id": "lesson-07-trigger-1497368914639-a198a223-7103-402b-85cc-882af7b2c151",
        "ctime": 1497368914639,
        "dataSource": "_none_",
        "dataId": "lesson-07-trigger",
        "category": "ALERT",
        "text": "Generates an alert on low median and high data point",
        "tags": {
            "HawkularMetrics": "MetricsCondition",
            "lesson": "7"
        },
        "trigger": {
            "tenantId": "tutorial",
            "id": "lesson-07-trigger",
            "name": "Lesson 07 Trigger",
            "description": "Generates an alert on low median and high data point",
            "type": "STANDARD",
            "eventType": "ALERT",
            "eventCategory": null,
            "eventText": null,
            "severity": "MEDIUM",
            "tags": {
                "HawkularMetrics": "MetricsCondition",
                "lesson": "7"
            },
            "autoDisable": true,
            "autoEnable": false,
            "autoResolve": false,
            "autoResolveAlerts": true,
            "autoResolveMatch": "ALL",
            "enabled": true,
            "firingMatch": "ALL",
            "source": "_none_"
        },
        "dampening": {
            "tenantId": "tutorial",
            "triggerId": "lesson-07-trigger",
            "triggerMode": "FIRING",
            "type": "STRICT",
            "evalTrueSetting": 1,
            "evalTotalSetting": 1,
            "evalTimeSetting": 0,
            "dampeningId": "tutorial-lesson-07-trigger-FIRING"
        },
        "evalSets": [
            [
                {
                    "evalTimestamp": 1497368914632,
                    "dataTimestamp": 1497368913841,
                    "type": "EXTERNAL",
                    "condition": {
                        "tenantId": "tutorial",
                        "triggerId": "lesson-07-trigger",
                        "triggerMode": "FIRING",
                        "type": "EXTERNAL",
                        "conditionSetSize": 2,
                        "conditionSetIndex": 1,
                        "conditionId": "tutorial-lesson-07-trigger-FIRING-2-1",
                        "alerterId": "HawkularMetrics",
                        "dataId": "alerterExpression01",
                        "expression": "{\"queries\": [{\"name\":\"qNow\", \"type\":\"gauge\", \"metrics\":[\"gauge-1\"], \"percentiles\":[\"60\"], \"duration\":\"45s\"}], \"frequency\":\"15s\", \"eval\":\"(q(qNow,%60) > 40)\"}"
                    },
                    "event": {
                        "eventType": "EVENT",
                        "tenantId": "tutorial",
                        "id": "b481c77d-e770-47ed-8b38-d87a918cd7cd",
                        "ctime": 1497368913841,
                        "dataSource": "_none_",
                        "dataId": "alerterExpression01",
                        "category": "MetricsCondition",
                        "text": "{q(qNow,%60)=52.0}"
                    }
                },
                {
                    "evalTimestamp": 1497368910624,
                    "dataTimestamp": 1497368908862,
                    "type": "THRESHOLD",
                    "condition": {
                        "tenantId": "tutorial",
                        "triggerId": "lesson-07-trigger",
                        "triggerMode": "FIRING",
                        "type": "THRESHOLD",
                        "conditionSetSize": 2,
                        "conditionSetIndex": 2,
                        "conditionId": "tutorial-lesson-07-trigger-FIRING-2-2",
                        "dataId": "hm_g_gauge-2",
                        "operator": "GTE",
                        "threshold": 70
                    },
                    "value": 97
                }
            ]
        ],
        "severity": "MEDIUM",
        "status": "OPEN",
        "lifecycle": [
            {
                "status": "OPEN",
                "user": "system",
                "stime": 1497368914639
            }
        ]
    }
]`

I think it are working now and it can be merged!

**Pull request merged**
