### PR TITLE
HWKALERTS-229 Filter unmatching triggerMode conditions on set*Conditions

### PR DESCRIPTION
**Pull request by lucasponce**
A filter to ignore those conditions that does not match with the triggerMode specified as parameter.

### CODE REVIEW

**Comment by jshaughn** [comment]
I'm not totally sure I agree with this approach.   I could just as easily think that the path parameter should be applied to the specified condition set.  In fact, I think in other places we do ensure the path params are applied to entities as needed.  Or, I think this should probably be an IllegalArgumentException, it seems to me it could catch a client issue, it seems odd to supply a condition set potentially scattered with conditions of the wrong trigger mode.

As for the filter, perhaps this should be done in the rest handler code as opposed to here.  At this point I would think we'd either apply the requested trigger-mode or throw an IllegalArgumentException.   If you feel strongly the filtering should be done as is, then we should probably filter first and ensure the remaining set is not empty before doing any work.

**Comment by lucasponce** [comment]
I like the suggestion to throw a 400 error in the rest handler if some condition with a different triggerMode is added.
I will re-arrange it in that way.

**Comment by lucasponce** [comment]
PR addressed.
I don't touch the Java API as it might be internal scenarios which might need this as discussed in JIRA.
So, instead an IllegalArgumentException it is responding a HTTP bad request.
Please, @jshaughn feel free to take a look.

**Comment by jshaughn** [comment]
Thanks @lucasponce .

**Pull request merged**
