### PR TITLE
Adapt to artifacts and packages renames in Metrics

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jshaughn @lucasponce changes targeted at Hawular M9

Could you please review, merge and release?

**Comment by ppalaga** [comment]
* unless you have more things for M9

**Comment by ppalaga** [comment]
@jshaughn @lucasponce would please somebody of you have a look what those test failures are about? https://travis-ci.org/hawkular/hawkular-alerts/builds/102470890#L6757-L6758

If you see a need to fix something, I'd be very glad if somebody of you could take over this PR, because I have close to zero background in Alerts and I have other things to do.

**Comment by lucasponce** [comment]
I'm relaunching the ci test and investigating.

**Comment by lucasponce** [comment]
Travis is starting to be less reliable than ever.
After a re-start things seems correct.
I'm going to merge the PR.

**Comment by ppalaga** [comment]
@lucasponce thanks.

FWIW, I saw these itest failures locally too - cca 1:4 fail/pass ratio.

**Pull request merged**
