### PR TITLE
fix hello-world so it can write to any server, not just localhost:8080

### PR DESCRIPTION
**Pull request by jmazzitelli**
if the server is bound to some other non-localhost, non-8080 port, be able to tell examples where to send the data.

The default remains the same, so nothing changes if you just "mvn validate" but now you can do this: "mvn validate -Dhost=192.168.1.100:8181" and it will work.

You can also set the tenant via -Dtenant.

### CODE REVIEW

**Comment by lucasponce** [comment]
Ah, probably you may want to change it in all the examples, as they follow the same pattern.

**Comment by jshaughn** [comment]
If you do this example you'll need to do all of the examples because people will expect it.

**Comment by jshaughn** [comment]
Ha, Lucas beat me by a few milliseconds

**Comment by jmazzitelli** [comment]
all examples are updated.

**Comment by jshaughn** [comment]
LGTM, merging as groovy files are outside the build...

**Pull request merged**
