### PR TITLE
Upgrade to Hawkular Parent 43, Commons 0.7.1.Final and latest Metrics srcdep

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jshaughn could you please have quick look? Just note that metrics 0.16.0.Final-SRC-revision-527e82f1107c41042e5d7bc01cab6f56e49ed590 is not in metrics master yet.

**Comment by jshaughn** [comment]
@ppalaga Thanks for the PR.  I don't think we need to update to Metrics 0.16.0 srcdep but perhaps we do.  I'd prefer not to wait for the 0.16.0 release before releasing Alerting.  I'll wait for @lucasponce to review the xsl changes as well.

**Comment by jshaughn** [comment]
Peter, I ran the i-tests just using thease changes but keeping metrics 0.15.0.Final.  Things looked good. Please close this PR, though, as I have created a separate one for @lucasponce to look at, that includes the version changes. Thanks -Jay

**Comment by ppalaga** [comment]
@jshaughn you are the boss here, why don't you close yourself? ;)

**Pull request closed without merging**
